# Generated by Django 5.1.6 on 2025-02-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header_eng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='header_ja',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='header_nep',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='header_eng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='header_ja',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='header_nep',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='header_eng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='header_ja',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='header_nep',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='header_eng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='header_ja',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='header_nep',
            field=models.CharField(max_length=255),
        ),
    ]
