# Generated by Django 5.1.6 on 2025-02-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_blog_content_nep_remove_job_content_nep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='ccontent_nep',
            new_name='ccontent_ne',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content_eng',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='header_eng',
            new_name='header_en',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='header_nep',
            new_name='header_ne',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='ccontent_nep',
            new_name='ccontent_ne',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='content_eng',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='header_eng',
            new_name='header_en',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='header_nep',
            new_name='header_ne',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='ccontent_nep',
            new_name='ccontent_ne',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content_eng',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='header_eng',
            new_name='header_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='header_nep',
            new_name='header_ne',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='header_eng',
            new_name='header_en',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='header_nep',
            new_name='header_ne',
        ),
    ]
