# Generated by Django 5.1.6 on 2025-02-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_ccontent_nep_blog_ccontent_ne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='ccontent_ne',
            new_name='content_ne',
        ),
    ]
