# Generated by Django 5.1.6 on 2025-02-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_ccontent_ne_news_content_ne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='ccontent_ne',
            new_name='content_ne',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='ccontent_ne',
            new_name='content_ne',
        ),
    ]
