# Generated by Django 5.1.6 on 2025-03-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_ccontent_ne_blog_content_ne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
